### ISSUE TITLE
No Validation For Email

### ISSUE THREAD

**Issue by kmarshall98** [info442-sp21/g-team#71]
**Description** When creating an account with the website, a user is prompted to create an account using their name, email, and password. With this input, there is a validation for whether it is an email format (characters + '@' + '.' + characters), but there is no validation of whether the email is correct or not. There should be a checker to make sure it is valid because it is more desirable to have real emails.

**Severity** Minor

**Environment** Safari on MacOs BigSur 11.2.3

**Steps to Reproduce**
1) Navigate to the home page
2) Press Sign Up and enter in your name
3) Enter an email and password
Expected Outcome: When entering a random email address it would validate it to make sure it is real or at least from a valid site.
Actual Outcome: User can enter anything that somewhat follows the email format
<img width="502" alt="Screen Shot 2021-05-25 at 2 50 48 PM" src="https://user-images.githubusercontent.com/46639384/119573678-75c51c80-bd69-11eb-9a53-839c4ba71b54.png">

**Comment by embascom** [comment]
- While this would be nice to have, it is out of scope for our project for this quarter

**Comment by cherimarie** [comment]
In general, the only real way to validate email addresses is to send a confirmation link to it that user must click. While most users will use commercial mail services (gmail, outlook, yahoo etc), plenty use custom domains. Now that there are also so many top level domains (.space, .photography, etc), trying to validate address via regex is so complicated that it's effectively impossible. Also, it's a relatively user-hostile validation, as we want users to feel that we trust them to know something so basic as their email, much like why it's not recommended to validate user names by length or inclusion of special characters rather than expecting that people will have last names like "X" or "Marquez Hernández". Form validation is a personal passion of mine because it's so important to user experience and cultural accessibility.
